apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  labels:
    app: customers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      restartPolicy: Always
      containers:
        - name: customers-service
          image: nazariazargul/petclinic-customers-service:4.0
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVER
              value: config-server
            - name: MYSQL_HOST
              value: mysql
            - name: spring.boot.admin.client.url
              value: admin-server:9091/spring-boot-admin
            - name: SPRING_ZIPKIN_BASEURL
              value: http://tracing-server:9411/
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
#      nodePort: 30003
